### PR TITLE
Add linux-headers to installed dependencies upon build

### PR DESCRIPTION
**Pull request by sharkwouter**
linux/limits.h was missing

### CODE REVIEW

**Review by MotoLegacy — APPROVED** [review]
LGTM

**Comment by fjtrujy** [comment]
I think you shouldn't add this package....
https://stackoverflow.com/questions/73168335/difference-between-include-limits-h-and-inlcude-linux-limits-h

`linux/limits.h` is not POSIX at all....

**Comment by sharkwouter** [comment]
> I think you shouldn't add this package.... https://stackoverflow.com/questions/73168335/difference-between-include-limits-h-and-inlcude-linux-limits-h
> 
> `linux/limits.h` is not POSIX at all....

I'll look into it, thanks!

**Comment by sharkwouter** [comment]
@fjtrujy actually, we build the Windows version with Cygwin because this entire codebase is not posix complient at all. Could we merge it as is? What changed is that alpine no longer bundles the linux headers with their build-base package. Otherwise there were no changes which caused this issue.

**Comment by fjtrujy** [comment]
> @fjtrujy actually, we build the Windows version with Cygwin because this entire codebase is not posix complient at all. Could we merge it as is? What changed is that alpine no longer bundles the linux headers with their build-base package. Otherwise there were no changes which caused this issue.

Ok, let's merge it!

**Review by fjtrujy — APPROVED** [review]

**Pull request merged**
