### PR TITLE
Automated windows build

### PR DESCRIPTION
**Pull request by sharkwouter**
This is still WIP, but this adds an action which builds pspsh and ubshost_fs for Windows using Cygwin.

### CODE REVIEW

**Comment by sharkwouter** [comment]
This is done now. Please review and test.

**Comment by sharkwouter** [comment]
@carstene1ns I tried it with msvc and msys, but it relies heavily on Posix specific stuff. I couldn't get it to build.

**Comment by dbeef** [comment]
I'm off the topic so this note may be out of the blue, but mingw packages are also available on Linux, so you could cross compile the Windows artifact in a posix environment without cygwin.

**Comment by sharkwouter** [comment]
I've just tested this once more. It does work. I will write instructions in the README and mark this PR as ready to review.

**Comment by sharkwouter** [comment]
This is ready now. The README has been turned into this: https://sharkwouter.github.io/psplinkusb/

The pspdev.github.io page will need to be updated to contain a link to it again.

**Review by fjtrujy — APPROVED** [review]
Good work @sharkwouter !

**Pull request merged**
