### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by sharkwouter**
At the moment running ``make release`` builds psplink for the firmware versions 1.0 and 1.5 as well as for newer versions. This is no longer useful. I've removed them and instead build only the one for newer firmware versions. This cleans up this repo significantly.

I've tested the resulting eboot and it seems to work like before.

### CODE REVIEW

**Comment by sharkwouter** [comment]
I accidentally included my other PR in this branch as well. Should I change that?

**Comment by carstene1ns** [comment]
The intention of this commit is really nice. However packing all in one commit without proper message makes it difficult to review.
I am going to recreate this locally to see if we can further remove things or if things are missing.

**Comment by sharkwouter** [comment]
Yeah, you're right. This is a big change and the changelog on github is a bit messy.

Here is a summary of the changes:

- The bootstrap directory was removed.
- The boot271 directory was renamed to bootstrap.
- Makefile.psp was removed.
- Makefile.oe was changed to build bootstrap instead of boot271.
- Makefile.oe was changed to use the release directory instead of release_oe.
- Makefile.oe was renamed to Makefile.psp.
- Makefile was changed to no longer build Makefile.oe, since it's no longer called that.
- Makefile.tools changed to no longer use the directories specific to  firmware versions 1.0 and 1.5.
- Some SFO files were removed from the repo, since they are generated upon building.
- .PBP and .SFO files were added to the .gitignore file.

Should I redo this in individual commits or would this summary allow you to review it?

I've reverted the commit with the udev rule. That should not have landed in here, but I used ``checkout -b`` on the wrong branch when I creating this PR.

**Comment by carstene1ns** [comment]
Thank you for the explanation, makes it really easier to review!
I would love to have this in at least 2 logical parts:
- removal of firmware 1.0/1.5 stuff
- moving the other stuff in place

About the .gitignore change: I have added this to #12, so it can be removed.

---

After both these PRs merged, I think we are fine to release 3.0.1 finally.

**Comment by sharkwouter** [comment]
No problem, I'll spend some time on this on the weekend. Should I base this PR on #12?

**Comment by carstene1ns** [comment]
Is not needed, but you could review and merge it, if you want.

**Pull request merged**
